### ISSUE TITLE
Program hang on updating progress bar

### ISSUE THREAD

**Issue by mishaturnbull** [mishaturnbull/EmailGUI#23]
Program hangs when instructed to update the progress bar in any manner.  Tried variations:
```python
# in gui.py
self.variables['progressbar'].set(self.variables['progressbar'].get() + 1)  # desirable
self.bar['value'] += 1
self.bar.step()
# in coordinator.py
self.gui.variables['progressbar'].set(self.gui.variables['progressbar'].get() + 1)
self.gui.bar['value'] += 1
self.bar.step()
```
Also after each above attempt I added `bar.update_idletasks()` and `bar.update()` with no progress.

Interestingly, this only seems to occur on the first update.  Running with Spyder4, I can achieve a complete batch send with the following procedure:
1. Start the program, enter configuration values, click Send
2. Wait for the first email to send
3. After the first email sends, program hangs.
4. Send a `KeyboardInterrupt` via either `CTRL+C` or with iPython's stop button
5. Program throws an exception (below) and continues.  The issue does not repeat for further progress bar updates.

KeyboardInterrupt exception:
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\program files (x86)\python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "D:/Random Programming Shit/Python/EmailBot/src/coordinator.py", line 59, in wrapped
    return cbfunc(self)
  File "D:\Random Programming Shit\Python\EmailBot\src\gui_callbacks.py", line 69, in handle_send
    coordinator.send()
  File "D:/Random Programming Shit/Python/EmailBot/src/coordinator.py", line 83, in send
    self.sender.run()
  File "D:\Random Programming Shit\Python\EmailBot\src\sender.py", line 128, in run
    if not self.workers:
KeyboardInterrupt
```

**Comment by mishaturnbull** [comment]
Patching together logs from `sys.stdout` and `sys.stderr`, this is the full recreating of events leading to this bug:

```python
runfile('D:/Random Programming Shit/Python/EmailBot/src/coordinator.py', wdir='D:/Random Programming Shit/Python/EmailBot/src')
Reloaded modules: emailbuilder, headers, sender, prereqs, helpers, gui, header_gui, gui_callbacks
coordinator.__init__: starting instantiation
coordinator.register_callbacks: registering verify
coordinator.register_callbacks: registering abort
coordinator.register_callbacks: registering browse
coordinator.register_callbacks: registering send
coordinator.register_callbacks: registering headers
coordinator.register_callbacks: registering autoselectmt
coordinator.register_callbacks: registering quickhelp
coordinator.register_callbacks: registering deephelp
coordinator.__init__: instantiation complete
coordinator: send command recieved
coordinator.retrieve_data_from_uis: pulling data
emailgui.dump_values_to_coordinator: beginning data dump
  processing amount with '10'
  dumping variable amount with value 10
  processing to with 'misha@slippery-weasel'
  dumping variable to with value misha@slippery-weasel
  processing account with 'spambot@127.0.0.1'
  dumping variable account with value spambot@127.0.0.1
  processing password with 'eatmyass'
  processing subject with 'Apology'
  dumping variable subject with value Apology
  processing text with 'Dear recipient,\nI am writing to apologize for incessantly writing you emails.  It\nmust be tiresome to spend all day deleting them.\n\nP.S. Please forgive me for sending this email.  I shall immediately\ndispatch a second email in apology.'
  dumping variable text with value Dear recipient,
I am writing to apologize for incessantly writing you emails.  It
must be tiresome to spend all day deleting them.

P.S. Please forgive me for sending this email.  I shall immediately
dispatch a second email in apology.
  processing server with '127.0.0.1:25'
  dumping variable server with value 127.0.0.1:25
  processing attachments with ''
  processing progressbar with 0
  processing mt_mode with 'none'
  dumping variable mt_mode with value none
  processing delay with '0'
  dumping variable delay with value 0
  processing mt_num with ''
  processing con_mode with 'con_once'
  dumping variable con_mode with value con_once
  processing max_retries with '5'
  dumping variable max_retries with value 5
emailsendhandler.create_worker_configurations: done: [10]
emailsendhandler.spawn_worker_threads: creating work pool
emailsendhandler.start_workers: sending start command to pool
Worker thread Thread #0 starting operation at 1538072959.0722637
Sending 0 at 1538072959.6641347
send: 'mail FROM:<spambot@127.0.0.1> size=595\r\n'
reply: b'250 Sender and size (595) OK - send RCPTs.\r\n'
reply: retcode (250); Msg: b'Sender and size (595) OK - send RCPTs.'
send: 'rcpt TO:<misha@slippery-weasel>\r\n'
reply: b'250 Recipient OK - send RCPT or DATA.\r\n'
reply: retcode (250); Msg: b'Recipient OK - send RCPT or DATA.'
send: 'data\r\n'
reply: b'354 OK, send data, end with CRLF.CRLF\r\n'
reply: retcode (354); Msg: b'OK, send data, end with CRLF.CRLF'
data: (354, b'OK, send data, end with CRLF.CRLF')
send: b'Content-Type: multipart/mixed; boundary="===============8136366572297041140=="\r\nMIME-Version: 1.0\r\nsender: spambot@127.0.0.1\r\nfrom: spambot@127.0.0.1\r\nsubject: Apology\r\n\r\n--===============8136366572297041140==\r\nContent-Type: text/plain; charset="us-ascii"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: 7bit\r\n\r\nDear recipient,\r\nI am writing to apologize for incessantly writing you emails.  It\r\nmust be tiresome to spend all day deleting them.\r\n\r\nP.S. Please forgive me for sending this email.  I shall immediately\r\ndispatch a second email in apology.\r\n--===============8136366572297041140==--\r\n.\r\n'
reply: b'250 Data received OK.\r\n'
reply: retcode (250); Msg: b'Data received OK.'
data: (250, b'Data received OK.')
Sent successfully!
emailsendhandler received notification of a sent email
coordinator recieved notification of email sent
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\program files (x86)\python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "D:/Random Programming Shit/Python/EmailBot/src/coordinator.py", line 59, in wrapped
    return cbfunc(self)
  File "D:\Random Programming Shit\Python\EmailBot\src\gui_callbacks.py", line 69, in handle_send
    coordinator.send()
  File "D:/Random Programming Shit/Python/EmailBot/src/coordinator.py", line 83, in send
    self.sender.run()
  File "D:\Random Programming Shit\Python\EmailBot\src\sender.py", line 128, in run
    if not self.workers:
KeyboardInterrupt
coordinator notification actions completed
emailsendhandler notification actions complete
Completed send callback
```
